services:
  - type: web
    name: p2-django
    env: python
    plan: free
    pythonVersion: 3.11.5
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --preload --log-file -
    postDeployCommand: |
      python manage.py migrate --noinput
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SECRET_KEY
        generate: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: p2-postgres
          property: connectionString

# Optional: uncomment if you use Redis
#      - key: REDIS_URL
#        fromService:
#          type: redis
#          name: p2-redis
#          property: connectionString

# Optional health check path (default is "/")
#    healthCheckPath: "/"

databases:
  - name: p2-postgres
    plan: free

